config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index]
  resources :project_launchings, only: [:new, :create]
  resources :features, only: [:new, :create]

  resources :card_addings, only: [:create]
  resources :card_forwardings, only: [:create]

  resources :wip_limit_changings, only: [:new, :create]
  resources :wip_limit_disablements, only: [:new, :create]

  resources :phase_spec_addings, only: [:new, :create]
  resources :phase_spec_removings, only: [:new, :create]

  resources :transition_settings, only: [:new, :create]
  resources :state_addings, only: [:new, :create]
  resources :state_removings, only: [:new, :create]

  get 'backlogs/:project_id_str', to: 'backlogs#show', as: :backlog
  get 'boards/:project_id_str', to: 'boards#show', as: :board
  get 'results/:project_id_str', to: 'results#show', as: :result

  get 'input_fields/new_transition', to: 'input_fields#new_transition', as: :new_transition_input_field
  get 'input_fields/new_state', to: 'input_fields#new_state', as: :new_state_input_field

  root 'projects#index'
end

app/models/view/board.rb
module View
  Board = Struct.new(:project_id, :project_name, :header, :body) do
    class << self

      def build(project_id)
        project_with_workflow = ProjectRecord.with_workflow(project_id)

        new(
          project_id,
          project_with_workflow.description_name,
          header(project_with_workflow),
          body(project_id)
        )
      end

      private

        def header(project_with_workflow)
          View::BoardHeader.build(
            project_with_workflow.project_id,
            project_with_workflow.phase_spec_records.to_a,
            project_with_workflow.state_records.to_a
          )
        end

        def body(project_id)
          cards = CardRecord.with_feature(project_id)
          View::BoardBody.build(project_id, cards)
        end
    end

    def step_size
      header.phase_states.size
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  layout 'board'

  def show
    @stats = View::Stats.build(params[:project_id_str], [:backlogs, :ships])
    @board = View::Board.build(params[:project_id_str])
    if @board.header.phases.any?
      render :show
    else
      render :bootstrap
    end
  end
end

app/views/boards/_board_body.html.erb
<tbody>
  <tr>
    <% phase_states.each do |state| -%>
      <td style="vertical-align: top">
        <% body.cards(state.phase_name, state.name).each do |card| -%>
          <div class="card">
            <div class="card-header text-muted">#<%= card.feature_number %></div>
            <div class="card-block">
              <h3 class="card-title"><%= card.summary %></h3>
              <p clsss="card-text text-muted"><%= card.detail.gsub(/\r\n|\n|\r/, '<br>').html_safe %></p>
              <%= form_for card.forward_card_command, url: card_forwardings_url do |f| -%>
                <%= f.hidden_field :project_id_str -%>
                <%= f.hidden_field :feature_id_str -%>
                <%= f.hidden_field :step_phase_name -%>
                <%= f.hidden_field :step_state_name -%>
                <%= f.submit raw('&#10140;'), class: 'btn btn-secondary-outline btn-block' -%>
              <% end -%>
            </div>
          </div>
        <% end -%>
      </td>
    <% end -%>
  </tr>
</tbody>

app/views/boards/_board_header.html.erb
<thead>
  <tr>
    <% phases.each do |phase| -%>
      <th colspan="<%= phase.state_size %>">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="header-phase"><%= phase.name %></span>&nbsp;<span class="label label-pill label-danger"><%= phase.wip_limit %></span>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" type="button" data-toggle="modal" data-target="modal-window">フェーズ名を変更する</a>
            <div class="dropdown-divider"></div>
            <%= link_to 'WIP制限の値を変更する',
              new_wip_limit_changing_url(project_id_str: project_id, phase_name: phase.name),
              remote: true,
              data: { toggle: 'modal', target: '#modal-window' },
              class: 'dropdown-item', type: 'button' %>
            <%= link_to 'WIP制限を解除する',
              new_wip_limit_disablement_url(project_id_str: project_id, phase_name: phase.name),
              remote: true,
              data: { toggle: 'modal', target: '#modal-window' },
              class: 'dropdown-item', type: 'button' %>
            <div class="dropdown-divider"></div>
            <%= link_to '新しいフェーズを前に追加する',
              new_phase_spec_adding_url(project_id_str: project_id, position: 'before', base_phase_name: phase.name),
              remote: true,
              data: { toggle: 'modal', target: '#modal-window' },
              class: 'dropdown-item', type: 'button' %>
            <%= link_to '新しいフェーズを後に追加する',
              new_phase_spec_adding_url(project_id_str: project_id, position: 'after', base_phase_name: phase.name),
              remote: true,
              data: { toggle: 'modal', target: '#modal-window' },
              class: 'dropdown-item', type: 'button' %>
            <% if phase.state_size == 0 %>
              <div class="dropdown-divider"></div>
              <%= link_to '推移を設定する',
                new_transition_setting_url(project_id_str: project_id, phase_name: phase.name),
                remote: true,
                data: { toggle: 'modal', target: '#modal-window' },
                class: 'dropdown-item', type: 'button' %>
            <% end -%>
            <div class="dropdown-divider"></div>
            <%= link_to 'フェーズを削除する',
              new_phase_spec_removing_url(project_id_str: project_id, phase_name: phase.name),
              remote: true,
              data: { toggle: 'modal', target: '#modal-window' },
              class: 'dropdown-item', type: 'button' %>
          </div>
        </div>
      </th>
    <% end -%>
  </tr>
  <tr>
    <% phase_states.each do |phase_state| -%>
      <th>
        <% if phase_state.none? -%>
          <%= phase_state.name %>
        <% else -%>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="header-phase"><%= phase_state.name %></span>
            </button>
            <div class="dropdown-menu">
              <%= link_to '新しい状態を前に追加する',
                new_state_adding_url(project_id_str: project_id, phase_name: phase_state.phase_name, position: 'before', base_state_name: phase_state.name),
                remote: true,
                data: { toggle: 'modal', target: '#modal-window' },
                class: 'dropdown-item', type: 'button' %>
              <%= link_to '新しい状態を後に追加する',
                new_state_adding_url(project_id_str: project_id, phase_name: phase_state.phase_name, position: 'after', base_state_name: phase_state.name),
                remote: true,
                data: { toggle: 'modal', target: '#modal-window' },
                class: 'dropdown-item', type: 'button' %>
              <div class="dropdown-divider"></div>
              <%= link_to '状態を削除する',
                new_state_removing_url(project_id_str: project_id, phase_name: phase_state.phase_name, state_name: phase_state.name),
                remote: true,
                data: { toggle: 'modal', target: '#modal-window' },
                class: 'dropdown-item', type: 'button' %>
            </div>
          </div>
        <% end -%>
      </th>
    <% end -%>
  </tr>
  <!-- modal window -->
  <div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="ModalWindow" aria-hidden="true"></div>
</thead>

app/views/boards/_body.html.erb
<tbody>
  <tr>
    <% phase_states.each do |state| -%>
      <td style="vertical-align: top">
        <% body.cards(state.phase_name, state.name).each do |card| -%>
          <div class="card">
            <div class="card-header text-muted">#<%= card.feature_number %></div>
            <div class="card-block">
              <h3 class="card-title"><%= card.summary %></h3>
              <p clsss="card-text text-muted"><%= card.detail.gsub(/\r\n|\n|\r/, '<br>').html_safe %></p>
              <%= form_for card.forward_card_command, url: card_forwardings_url do |f| -%>
                <%= f.hidden_field :project_id_str -%>
                <%= f.hidden_field :feature_id_str -%>
                <%= f.hidden_field :step_phase_name -%>
                <%= f.hidden_field :step_state_name -%>
                <%= f.submit raw('&#10140;'), class: 'btn btn-secondary-outline btn-block' -%>
              <% end -%>
            </div>
          </div>
        <% end -%>
      </td>
    <% end -%>
  </tr>
</tbody>

app/views/boards/_new_phase_spec_adding.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4 class="modal-title" id="modal-window"><%= @command.describe %></h4>
    </div>
    <%= form_for @command, url: phase_spec_addings_url, remote: true do |f| %>
      <%= render partial: 'application/modal_window_form_errors', locals: { errors: f.object.errors } %>
      <%= f.hidden_field :project_id_str %>
      <%= f.hidden_field :position %>
      <%= f.hidden_field :base_phase_name %>
      <div class="modal-body">
        <div class="form-group row">
          <%= f.label '名前', class: 'col-sm-6 control-label' %>
          <div class="col-sm-6">
            <%= f.text_field :phase_name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label 'WIP制限', class: 'col-sm-6 control-label' %>
          <div class="col-sm-6">
            <%= f.number_field :wip_limit_count, class: 'form-control' %>
          </div>
        </div>
        <% command_name = f.object.model_name.to_s.underscore %>
        <% if f.object.state_names.empty? %>
          <div id="new-transition-link">
            <%= link_to '推移を設定', new_transition_input_field_url(command_name: command_name), remote: true %>
          </div>
        <% end -%>
        <div id="transition-form-control">
          <% if f.object.state_names.any? %>
            <%= render partial: 'boards/transition_form_control', locals: {
              command_name: command_name,
              state_names: f.object.state_names
            } %>
          <% end -%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit '追加する', class: 'btn btn-primary' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/boards/_new_phase_spec_removing.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4 class="modal-title" id="modal-window">フェーズの削除</h4>
    </div>
    <%= form_for @command, url: phase_spec_removings_url, remote: true do |f| %>
      <%= render partial: 'application/modal_window_form_errors', locals: { errors: f.object.errors } %>
      <%= f.hidden_field :project_id_str %>
      <%= f.hidden_field :phase_name %>
      <div class="modal-body">
        <p>「<%= @command.phase_name %>」フェーズを削除します。</p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit '削除する', class: 'btn btn-danger' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/boards/_new_state_adding.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4 class="modal-title" id="modal-window"><%= @command.describe %></h4>
    </div>
    <%= form_for @command, url: state_addings_url, remote: true do |f| %>
      <%= render partial: 'application/modal_window_form_errors', locals: { errors: f.object.errors } %>
      <%= f.hidden_field :project_id_str %>
      <%= f.hidden_field :phase_name %>
      <%= f.hidden_field :position %>
      <%= f.hidden_field :base_state_name %>
      <div class="modal-body">
        <div class="form-group row">
          <%= f.label '名前', class: 'col-sm-6 control-label' %>
          <div class="col-sm-6">
            <%= f.text_field :state_name, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit '追加する', class: 'btn btn-primary' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/boards/_new_transition_setting.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4 class="modal-title" id="modal-window">「<%= @command.phase_name %>」に推移を設定</h4>
    </div>
    <%= form_for @command, url: transition_settings_url, remote: true do |f| %>
      <%= render partial: 'application/modal_window_form_errors', locals: { errors: f.object.errors } %>
      <%= f.hidden_field :project_id_str %>
      <%= f.hidden_field :phase_name %>
      <div class="modal-body">
        <%= render partial: 'boards/transition_form_control', locals: {
          command_name: f.object.model_name.to_s.underscore,
          state_names: f.object.state_names
        } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit '設定する', class: 'btn btn-primary' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/boards/_new_wip_limit_changing.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4 class="modal-title" id="modal-window">WIP制限の変更</h4>
    </div>
    <%= form_for @command, url: wip_limit_changings_url, remote: true do |f| %>
      <%= render partial: 'application/modal_window_form_errors', locals: { errors: f.object.errors } %>
      <%= f.hidden_field :project_id_str %>
      <%= f.hidden_field :phase_name %>
      <div class="modal-body">
        <div class="form-group row">
          <%= f.label :wip_limit_count, class: 'col-sm-6 control-label' %>
          <div class="col-sm-6">
            <%= f.number_field :wip_limit_count, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit '変更する', class: 'btn btn-primary' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/boards/_new_wip_limit_disablement.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4 class="modal-title" id="modal-window">WIP制限の解除</h4>
    </div>
    <%= form_for @command, url: wip_limit_disablements_url, remote: true do |f| %>
      <%= render partial: 'application/modal_window_form_errors', locals: { errors: f.object.errors } %>
      <%= f.hidden_field :project_id_str %>
      <%= f.hidden_field :phase_name %>
      <div class="modal-body">
        <p>「<%= @command.phase_name %>」フェーズのWIP制限を解除します。</p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit '解除する', class: 'btn btn-primary' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/boards/_page_header.html.erb
<section class="page-header">
  <div class="row">
    <div class="col-md-8">
      <h1><%= link_to @board.project_name, projects_url %> Board</h1>
    </div>
    <div class="col-md-4">
      <ul class="nav nav-pills pull-right">
        <li class="nav-item">
          <%= link_to(backlog_url(project_id_str: @board.project_id), class: 'nav-link') do %>
            <span class="label label-default"><%= @stats.backlogs %></span>&nbsp;Backlogs
          <% end -%>
        </li>
        <li class="nav-item">
          <%= link_to(result_url(project_id_str: @board.project_id), class: 'nav-link') do %>
            <span class="label label-default"><%= @stats.ships %></span>&nbsp;Ships
          <% end -%>
        </li>
      </ul>
    </div>
  </div>
</section>

app/views/boards/_state_form_control.html.erb
<div class="form-group row">
  <%= label_tag '状態', nil, class: 'col-sm-6 control-label' %>
  <div class="col-sm-6">
    <%= text_field_tag "#{command_name}[state_names][]", state_name, placeholder: '作業中/完了など',class: 'form-control' %>
  </div>
</div>

app/views/boards/_transition_form_control.html.erb
<% state_names.each do |state_name| %>
  <%= render partial: 'boards/state_form_control', locals: {
    command_name: command_name,
    state_name: state_name
  } %>
<% end -%>
<div id="state-form-controls"></div>
<div><%= link_to '状態を追加', new_state_input_field_url(command_name: command_name), remote: true %></div>

app/views/boards/bootstrap.html.erb
<%= render 'page_header' %>
<section class="content">
  <div class="jumbotron">
    <h2 class="display-1">かんばんボード</h2>
    <p class="lead">ワークフローを設定してボードを使えるようにしましょう。</p>
    <hr class-"m-y-md">
    <%= link_to '最初のフェーズを追加する',
      new_phase_spec_adding_url(project_id_str: @board.project_id_str),
      remote: true,
      data: { toggle: 'modal', target: '#modal-window' },
      class: 'btn btn-primary btn-lg', type: 'button' %>
  </div>
  <!-- modal window -->
  <div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="ModalWindow" aria-hidden="true"></div>
</section>

app/views/boards/show.html.erb
<%= render 'page_header' %>
<% board_section_style = @board.header.phase_states.size >= 7 ?
  '' : " style='width: #{@board.header.phase_states.size * 180}px;'" %>
<section class="content"<%= raw(board_section_style) %>>
  <table class="kanban table">
    <%= render partial: 'board_header', locals: {
      project_id: @board.project_id,
      phases: @board.header.phases,
      phase_states: @board.header.phase_states
    } %>
    <%= render partial: 'board_body', locals: {
      phase_states: @board.header.phase_states,
      body: @board.body
    } %>
  </table>
</div>