config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index]
  resources :project_launchings, only: [:new, :create]
  resources :features, only: [:new, :create]

  resources :card_addings, only: [:create]
  resources :card_forwardings, only: [:create]

  resources :wip_limit_changings, only: [:new, :create]
  resources :wip_limit_disablements, only: [:new, :create]

  resources :phase_spec_addings, only: [:new, :create]
  resources :phase_spec_removings, only: [:new, :create]

  resources :transition_settings, only: [:new, :create]
  resources :state_addings, only: [:new, :create]
  resources :state_removings, only: [:new, :create]

  get 'backlogs/:project_id_str', to: 'backlogs#show', as: :backlog
  get 'boards/:project_id_str', to: 'boards#show', as: :board
  get 'results/:project_id_str', to: 'results#show', as: :result

  get 'input_fields/new_transition', to: 'input_fields#new_transition', as: :new_transition_input_field
  get 'input_fields/new_state', to: 'input_fields#new_state', as: :new_state_input_field

  root 'projects#index'
end

app/models/view/backlog.rb
module View
  Backlog = Struct.new(:project_id, :project_name, :features) do

    def self.build(project_id)
      project = ProjectRecord.find_by(project_id: project_id)
      features = BackloggedFeatureRecord
                   .with_project(project.project_id)
                   .map {|r| Feature.new(r) }
      new(
        project.project_id,
        project.name,
        features
      )
    end

    Feature = Struct.new(:number, :project_id, :feature_id, :summary, :detail) do

      def initialize(hash)
        super(
          *hash.values_at(
            'number',
            'project_id',
            'feature_id',
            'description_summary',
            'description_detail'
          )
        )
      end

      def add_card_command
        AddCardCommand.new(
          project_id_str: project_id,
          feature_id_str: feature_id
        )
      end
    end
  end
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController

  def show
    @stats = View::Stats.build(params[:project_id_str], [:wip, :ships])
    @backlog = View::Backlog.build(params[:project_id_str])
  end
end

app/views/backlogs/show.html.erb
<section class="page-header">
  <div class="row">
    <div class="col-md-8">
      <h1><%= link_to @backlog.project_name, projects_url %> Backlog</h1>
    </div>
    <div class="col-md-4">
      <div class="row">
        <ul class="nav nav-pills pull-right">
          <li class="nav-item">
            <%= link_to(board_url(project_id_str: @backlog.project_id), class: 'nav-link') do %>
              <span class="label label-default"><%= @stats.wip %></span>&nbsp;WIP
            <% end -%>
          </li>
          <li class="nav-item">
            <%= link_to(result_url(project_id_str: @backlog.project_id), class: 'nav-link') do %>
              <span class="label label-default"><%= @stats.ships %></span>&nbsp;Ships
            <% end -%>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to 'Add feature', new_feature_url(project_id_str: @backlog.project_id), class: 'btn btn-secondary pull-right' %>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover ids actions">
        <thead>
          <tr>
            <th>#</th>
            <th>Summary</th>
            <th>Detail</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @backlog.features.each do |feature| %>
            <tr>
              <td><%= feature.number %></td>
              <td><%= feature.summary %></td>
              <td><%= feature.detail %></td>
              <td>
                <%= form_for feature.add_card_command, url: card_addings_url do |f| %>
                  <%= f.hidden_field :project_id_str %>
                  <%= f.hidden_field :feature_id_str %>
                  <%= f.submit 'Todo', class: 'btn btn-primary-outline pull-right' %>
                <% end -%>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>
  </div>
</section>