config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index]
  resources :project_launchings, only: [:new, :create]
  resources :features, only: [:new, :create]

  resources :card_addings, only: [:create]
  resources :card_forwardings, only: [:create]

  resources :wip_limit_changings, only: [:new, :create]
  resources :wip_limit_disablements, only: [:new, :create]

  resources :phase_spec_addings, only: [:new, :create]
  resources :phase_spec_removings, only: [:new, :create]

  resources :transition_settings, only: [:new, :create]
  resources :state_addings, only: [:new, :create]
  resources :state_removings, only: [:new, :create]

  get 'backlogs/:project_id_str', to: 'backlogs#show', as: :backlog
  get 'boards/:project_id_str', to: 'boards#show', as: :board
  get 'results/:project_id_str', to: 'results#show', as: :result

  get 'input_fields/new_transition', to: 'input_fields#new_transition', as: :new_transition_input_field
  get 'input_fields/new_state', to: 'input_fields#new_state', as: :new_state_input_field

  root 'projects#index'
end

app/models/add_card_form.rb
class AddCardForm
  include ActiveModel::Model

  attr_accessor :project_id_str, :feature_id_str

  validates :project_id_str, presence: true
  validates :feature_id_str, presence: true

  def project_id
    Project::ProjectId.new(project_id_str)
  end

  def feature_id
    Feature::FeatureId.new(feature_id_str)
  end

  def prefer(service)
    service.add_card(project_id, feature_id)
  end
end

app/models/backlogged_feature_record.rb
class BackloggedFeatureRecord < ActiveRecord::Base
  class << self

    def with_project(project_id)
      sql = <<-EOSQL
        SELECT
          feature.*
        FROM
          feature_records AS feature
            JOIN backlogged_feature_records AS backlogged
              ON feature.id = backlogged.feature_record_id
            LEFT OUTER JOIN card_records AS card
              ON feature.feature_id = card.feature_id
            LEFT OUTER JOIN shipped_feature_records AS shipped
              ON feature.id = shipped.feature_record_id
        WHERE
          feature.project_id = ?
            AND backlogged.id IS NOT NULL
            AND card.id IS NULL
            AND shipped.id IS NULL
        ORDER BY feature.id
      EOSQL
      connection.select_all(sanitize_sql_array([sql, project_id])).to_hash
    end

    def count(project_id)
      with_project(project_id).size
    end
  end
end

app/models/board_record.rb
class BoardRecord < ActiveRecord::Base
  has_many :card_records
end

app/models/card_record.rb
class CardRecord < ActiveRecord::Base
  class << self

    def with_feature(project_id)
      sql = <<-EOSQL
        SELECT
          card.*, feature.*
        FROM
          board_records AS board
            JOIN card_records AS card
              ON board.id = card.board_record_id
            JOIN feature_records AS feature
              ON card.feature_id = feature.feature_id
        WHERE
          board.project_id = ?
      EOSQL
      connection.select_all(sanitize_sql_array([sql, project_id])).to_hash
    end

    def count(project_id)
      sql = <<-EOSQL
        SELECT
          COUNT(*) AS count
        FROM
          board_records AS board
            JOIN card_records AS card
              ON board.id = card.board_record_id
        WHERE
          board.project_id = ?
      EOSQL
      connection.select_one(sanitize_sql_array([sql, project_id])).to_hash['count']
    end
  end
end

app/models/feature_record.rb
class FeatureRecord < ActiveRecord::Base
  has_one :backlogged_feature_record, dependent: :destroy
  has_one :wip_feature_record, dependent: :destroy
  has_one :shipped_feature_record, dependent: :destroy

  class << self

    def result(project_id)
      includes(
        :backlogged_feature_record,
        :wip_feature_record,
        :shipped_feature_record
      )
        .where(project_id: project_id)
        .where.not(backlogged_feature_records: { id: nil })
        .where.not(wip_feature_records: { id: nil })
        .where.not(shipped_feature_records: { id: nil })
    end
  end

  def feature_id
    id
  end

  def summary
    description_summary
  end

  def detail
    description_detail
  end
end

app/models/phase_spec_record.rb
class PhaseSpecRecord < ActiveRecord::Base
  belongs_to :project_record
  delegate :state_records, to: :project_record

  def states
    states_records
  end
end

app/models/project_record.rb
class ProjectRecord < ActiveRecord::Base
  has_many :phase_spec_records, -> { order(:order) }
  has_many :state_records, -> { order(:order) }

  class << self

    def with_workflow(project_id)
      eager_load(:phase_spec_records, :state_records)
        .find_by(project_id: project_id)
    end
  end

  def name
    description_name
  end

  def goal
    description_goal
  end
end

app/models/shipped_feature_record.rb
class ShippedFeatureRecord < ActiveRecord::Base
  class << self

    def count(project_id)
      FeatureRecord
        .includes(:shipped_feature_record)
        .where(project_id: project_id)
        .where.not(shipped_feature_records: { id: nil })
        .count
    end
  end
end

app/models/state_record.rb
class StateRecord < ActiveRecord::Base
end

app/models/wip_feature_record.rb
class WipFeatureRecord < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ServiceRegistry
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController

  def show
    @stats = View::Stats.build(params[:project_id_str], [:wip, :ships])
    @backlog = View::Backlog.build(params[:project_id_str])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  layout 'board'

  def show
    @stats = View::Stats.build(params[:project_id_str], [:backlogs, :ships])
    @board = View::Board.build(params[:project_id_str])
    if @board.header.phases.any?
      render :show
    else
      render :bootstrap
    end
  end
end

app/controllers/card_addings_controller.rb
class CardAddingsController < ApplicationController

  def create
    command = AddCardCommand.new(command_params)
    if command.execute(board_service)
      redirect_to board_url(project_id_str: command.project_id_str), notice: 'Card added'
    else
      redirect_to backlog_url(project_id_str: command.project_id_str), alert: command.errors.full_messages.join('<br>')
    end
  end

  private

    def command_params
      params.require(:add_card_command).permit(
        :project_id_str, :feature_id_str
      )
    end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController

  def new
    @command = AddFeatureCommand.new.tap do |c|
      c.project_id_str = params[:project_id_str]
    end
  end

  def create
    @command = AddFeatureCommand.new(command_params)
    if @command.execute(feature_service)
      redirect_to backlog_url(@command.project_id_str), notice: 'Feature added to backlog!'
    else
      flash.now[:alert] = 'Ooops!'
      render :new
    end
  end

  private

    def command_params
      params.require(:add_feature_command).permit(
        :project_id_str, :summary, :detail
      )
    end
end

app/controllers/input_fields_controller.rb
class InputFieldsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = ProjectRecord.all
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def show
    @stats = View::Stats.build(params[:project_id_str], [:backlogs, :wip])
    @result = View::Result.build(params[:project_id_str])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/controllers/state_addings_controller.rb
class StateAddingsController < ApplicationController

  def new
    @command = AddStateCommand.new(
      project_id_str: params[:project_id_str],
      phase_name: params[:phase_name],
      position: params[:position],
      base_state_name: params[:base_state_name]
    )
    render 'modal_window_form', locals: { path: 'boards/new_state_adding' }
  end

  def create
    @command = AddStateCommand.new(command_params)
    if @command.execute(phase_spec_service)
      flash[:notice] = 'フェーズに状態を追加しました。'
      render 'redirect_from_modal', locals: { to: board_url(@command.project_id_str) }
    else
      render 'modal_window_form', locals: { path: 'boards/new_state_adding' }
    end
  end

  private

    def command_params
      params.require(:add_state_command).permit(
        :project_id_str, :phase_name, :state_name,
        :position, :base_state_name
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/features/new.html.erb
<section class="page-header">
  <div class="row">
    <div class="col-md-12">
      <h1>新しい機能をバックログに追加します。</h1>
    </div>
  </div>
</section>
<section class="content">
  <%= form_for @command, url: features_url do |f| %>
    <%= f.hidden_field :project_id_str %>
    <div class="form-group row">
      <%= f.label :summary, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :summary, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :detail, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.text_area :detail, rows: 5, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-offset-4 col-sm-8">
        <%= f.submit 'Add new feature to backlog', class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  <% end -%>
</section>

app/views/input_fields/new_state.js.erb
$('#state-form-controls').append("<%= escape_javascript(render(partial: 'boards/state_form_control', locals: { command_name: params[:command_name], state_name: nil })) %>")

app/views/input_fields/new_transition.js.erb
$('#transition-form-control').append("<%= escape_javascript(render(partial: 'boards/transition_form_control', locals: { command_name: params[:command_name], state_names: [nil, nil] })) %>")
$('#new-transition-link').remove();

app/views/projects/index.html.erb
<section class="page-header">
  <div class="row">
    <div class="col-md-8">
      <h1>プロジェクト</h1>
    </div>
    <div class="col-md-4">
      <%= link_to 'Launch new project', new_project_launching_url, class: 'btn btn-secondary pull-right' %>
    </div>
  </div>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <table class="table actions">
        <thead>
          <tr>
            <th>Name</th>
            <th>Goal</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.name %></td>
              <td><%= project.goal %></td>
              <td>
                <div class="pull-right">
                  <%= link_to 'Board', board_url(project.project_id) %> |
                  <%= link_to 'Backlog', backlog_url(project.project_id) %>
                </div>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>
  </div>
</section>